### ISSUE TITLE
bcbio-nextgen-vm not installing on MacOSX

### ISSUE THREAD

**Issue by Double-O-ren** [chapmanb/bcbio-nextgen-vm#100]
I'm trying to setup the VM on a mac (Miniconda3-latest-MacOSX-x86_64.sh) and I get the following error: 
```
Fetching package metadata: ......
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint: 
[      COMPLETE      ]|###################################################################################################################################################################################################################################################| 100%
Hint: the following combinations of packages create a conflict with the
remaining packages:
  - python 3.4*
  - bcbio-nextgen-vm
```

I also tried 
Miniconda-3.9.1-MacOSX-x86_64.sh
but got another error
Python 2.7.9 :: Continuum Analytics, Inc.
creating default environment...
```
Traceback (most recent call last):
  File "/Users/oren/install/bcbio-vm/anaconda/pkgs/conda-3.9.1-py27_0/lib/python2.7/site-packages/conda/install.py", line 36, in <module>
    import subprocess
  File "/Users/oren/install/bcbio-vm/anaconda/pkgs/python-2.7.9-1/lib/python2.7/subprocess.py", line 430, in <module>
    import pickle
  File "/Users/oren/install/bcbio-vm/anaconda/pkgs/python-2.7.9-1/lib/python2.7/pickle.py", line 1266, in <module>
    import binascii as _binascii
ImportError: dlopen(/Users/oren/install/bcbio-vm/anaconda/pkgs/python-2.7.9-1/lib/python2.7/lib-dynload/binascii.so, 2): Library not loaded: @loader_path/../../libz.1.dylib
  Referenced from: /Users/oren/install/bcbio-vm/anaconda/pkgs/python-2.7.9-1/lib/python2.7/lib-dynload/binascii.so
  Reason: image not found
```

I have no problems when I try to install using this version of conda: 
Miniconda-latest-Linux-x86_64.sh

Can you please advise? 
Thanks

**Comment by roryk** [comment]
Hi @Double-O-ren,

AFAIK we still don't have a good solution for the permissions issue for OSX yet, so you might end up getting it to install and still not being able to do what you want. That being said, at least the install should work. Is this error cropping up when you run:

```bash
~/install/bcbio-vm/anaconda/bin/conda install --yes -c bcbio bcbio-nextgen-vm
```

**Comment by chapmanb** [comment]
Oren;
Seconding Rory's comments, the Docker bcbio-vm doesn't yet work on Mac OSX. You can use bcbio-vm to control AWS jobs, not for for running things locally on Macs. Like Rory, just want to set expectations so you're not wasting time.

For the install issues, the first problem is that bcbio only works with Python 2, so don't use Miniconda3 installers, which default to Python 3. The second issue looks to be something similar to that discussed here (https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/Wc-1h9umfVQ). Is it possible you have a broken/half finished Anaconda install from the previous run? You could try to do:
```
rm -rf /Users/oren/install/bcbio-vm/anaconda/
wget https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh
bash Miniconda-latest-MacOSX-x86_64.sh
```
Hope this fixes it for you.

**Comment by guillermo-carrasco** [comment]
`bcbio-nextgen-vm` installs cleanly in Mac OSX Yosemite following instructions in the [README section for Mac OSX](https://github.com/chapmanb/bcbio-nextgen-vm#mac-osx-docker-support). Main problem is indeed that you would require to install Python 2 rather than Python 3 Miniconda distribution.

I'll close the issue, please let us know and feel free to re-open it if you still have problems.
