### ISSUE TITLE
parallele execution of cutadapt

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen-vm#107]
Hi chapmanb,
I have a question is possible to run cut adapt in the rnaseq pipeline on multiple samples simultaneously.

I have tried bcbio_vm.py ipython ../config/hzl_noaln.yaml torque batch -r walltime=00:30:00 -r nodes=1:ppn=16 -r mem=32gb

but it still run one sample at a time

thanks for your suggestion!

**Comment by chapmanb** [comment]
Sorry about the issue and lack of parallelization. I pushed a fix which should resolve this, but will need to create a new docker container to make it available on bcbio-vm. I'll also tackle #108, then push a new container that fixes both issues. Thanks again for reporting the problem.

**Comment by apastore** [comment]
I have to thank!

I will test it when you have a new immage!
