### ISSUE TITLE
scalpel fail libbamtools.so.2.3.0: cannot open shared object file

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen-vm#108]
Hi Chapmanb,

scalpel is missing one library and fail

Thanks!

Genotyping with Scalpel
[2015-08-24T22:11Z] Local date and time: Mon Aug 24 22:11:42 2015
[2015-08-24T22:11Z]
[2015-08-24T22:11Z] Program: scalpel (micro-assembly variant detection)
[2015-08-24T22:11Z] Version: 0.3.1(beta)
[2015-08-24T22:11Z] Contact: Giuseppe Narzisi <gnarzisi@nygenome.org>
[2015-08-24T22:11Z]
[2015-08-24T22:11Z] ***START ANALYSIS***
[2015-08-24T22:11Z] Genotyping with Scalpel
[2015-08-24T22:11Z] -- Print parameters to /mnt/work/mutect/2/tx/tmppNYdBC/tx/tmp7aAJmX/parameters.txt
[2015-08-24T22:11Z] Loading targets from BED file...3 targets (filtered 0 overlapping).
[2015-08-24T22:11Z] /usr/local/Cellar/scalpel/0.3.1_5-2d23b7/bamtools-2.3.0/bin/bamtools: error while loading shared libraries: libbamtools.so.2.3.0: cannot open shared object file: No such file or directory
[2015-08-24T22:11Z] Command failure: extract SAM header (/usr/local/Cellar/scalpel/0.3.1_5-2d23b7/bamtools-2.3.0/bin/bamtools header -in /mnt/work/mutect/2/tx/tmppNYdBC/tx/tmp7aAJmX/bamfile.bam > /mnt/work/mutect/2/tx/tmppNYdBC/tx/tmp7aAJmX/header.txt)...
[2015-08-24T22:11Z] child exited with value 127
Assembly Exons
[2015-08-24T22:11Z] start assembly of 3 regions.
[2015-08-24T22:11Z] stepSize: 3
[2015-08-24T22:11Z] 1. [0..2]
[2015-08-24T22:11Z] Command failure: microassembly (/usr/local/Cellar/scalpel/0.3.1_5-2d23b7/Microassembler/Microassembler -R -I -C -F 10000 -k 25 -K 90 -M 3 -l 25 -c 3 -x 0.01 -d 1 -u 10000 -b 1 -p /mnt/work/mutect/2/tx/tmppNYdBC/tx/tmp7aAJmX -m bamfile.bam -g readgroups.txt  -r regions-0-2.fa >/mnt/work/mutect/2/tx/tmppNYdBC/tx/tmp7aAJmX/logs/regions-0-2.fa.log 2>&1)...
[2015-08-24T22:11Z] child exited with value 127
[2015-08-24T22:11Z] Merge DBs...
[2015-08-24T22:11Z] Load reference coverage...
[2015-08-24T22:11Z] Load loc2keys DB...
[2015-08-24T22:11Z] Computing hom/het state...
[2015-08-24T22:11Z] Num. Homozygous: 0
[2015-08-24T22:11Z] Num. Heterozygous: 0
[2015-08-24T22:11Z]
[2015-08-24T22:11Z] Dfs limit: 0
[2015-08-24T22:11Z] Partial alignments: 0
[2015-08-24T22:11Z] Cycles: 0
[2015-08-24T22:11Z] OK assemblies: 0
[2015-08-24T22:11Z] Exceptions: 0
[2015-08-24T22:11Z] Repeats: 0

**Comment by chapmanb** [comment]
Thanks for the heads up on the problem. I pushed a fixed version of scalpel that uses the global bamtools instead of the local one and created a new Docker container for this and #107. As a heads up, scalpel is slow on larger datasets and we haven't been using it by default for this reason. It does do a good job of detecting indels, but I wanted you to be aware of the computational effort involved. Thanks again.

**Comment by alexvat** [comment]
Hi, I am running into a similar error. How exactly did you solve this issue?

**Comment by chapmanb** [comment]
Alexandra;
Can you provide more details about the environment you're seeing this error? Is this from a bcbio or bioconda installation? If so, happy to debug more. If you have a different install, I can recommend using the bioconda package (https://bioconda.github.io/):
```
conda install -c bioconda scalpel
```
Hope this helps.

**Comment by alexvat** [comment]
Hi. I had downloaded scalpel from http://scalpel.sourceforge.net/manual.html and I had the error.
Seems to works just fine with the version installed using conda. 
Thanks for your quick reply.

**Comment by alexvat** [comment]
Hi. I have now the following error:
samtools: symbol lookup error: /lib64/libncurses.so.5: undefined symbol: _nc_putchar
after starting the assembly procedure. 
Let me know if you have any idea how I can fix that.

**Comment by chapmanb** [comment]
Alexandra;
Sorry about that, it looks like you didn't get the right version of ncurses from the conda `r` channel (https://github.com/bioconda/bioconda-recipes/issues/637). You could fix with:
```
conda install -c r ncurses
```
Hope this gets things working cleanly for you.

**Comment by Dr-east** [comment]
I also have a similar problem like:
***START ANALYSIS***
-- Print parameters to /home/zhengsai/chr1/parameters.txt
Loading targets region: chr1:0-195471971
Loading genome from FASTA file...66 sequences.
Assembly Exons
start assembly of 1954716 regions.
stepSize: 390944
** 0 started, pid: 42302
1. [0..390943]
** 390944 started, pid: 42303
2. [390944..781887]
** 781888 started, pid: 42305
3. [781888..1172831]
Command failure: microassembly (/home/zhengsai/scalpel-0.5.3/Microassembler/Microassembler -R -I -C -F 1000000 -k 25 -K 90 -M 3 -l 25 -c 5 -x 0.01 -d 2 -u 10000 -b 1 -p /home/zhengsai/chr1 -m bamfile.bam -g readgroups.txt  -r regions-0-390943.fa >/home/zhengsai/chr1/logs/regions-0-390943.fa.log 2>&1)...
child exited with value 127
** 1172832 started, pid: 42308
4. [1172832..1563775]
Command failure: microassembly (/home/zhengsai/scalpel-0.5.3/Microassembler/Microassembler -R -I -C -F 1000000 -k 25 -K 90 -M 3 -l 25 -c 5 -x 0.01 -d 2 -u 10000 -b 1 -p /home/zhengsai/chr1 -m bamfile.bam -g readgroups.txt  -r regions-390944-781887.fa >/home/zhengsai/chr1/logs/regions-390944-781887.fa.log 2>&1)...
child exited with value 127

please help me

**Comment by chapmanb** [comment]
If this is a scalpel issue not related to bcbio your best bet is to ask the scalpel team: http://scalpel.sourceforge.net/ Hope this helps.

**Comment by clersdom** [comment]
Hi all, 
I am having the same error `Command failure: microassembly`. On checking the path for the 
'microassembler' program, there is no executable file for it. 
Any help with this?
Many thanks!

**Comment by roryk** [comment]
Hi @clersdom,

Could you post the whole error? It's tough to know exactly what is happening without it. Thank you!

**Comment by clersdom** [comment]
Hi @roryk ,

Please see below the error:

Program: scalpel-discovery (micro-assembly variant detection)
Version: 0.5.4 (beta), January 11 2018
Contact: Giuseppe Narzisi <gnarzisi@nygenome.org>

***MAIN ANALYSIS***
-- Print parameters to /outdir/main/parameters.txt
-- Detect mutations on normal
-- Print parameters to /outdir/main/normal/parameters.txt
Loading targets from BED file...185636 targets (filtered 0 overlapping).
Assembly Exons
start assembly of 401216 regions.
stepSize: 401216
** 0 started, pid: 624240
1. [0..401215]
Command failure: microassembly (/rds/general/user/cd3417/home/anaconda3/envs/analysis_Clara/share/scalpel-0.5.4-1/Microassembler/Microassembler -R -I -C -F 1000000 -k 25 -K 90 -M 3 -l 25 -c 5 -x 0.01 -d 2 -u 10000 -b 1 -p /outdir/main/normal -m bamfile.bam -g readgroups.txt  -r regions-0-401215.fa >/outdir/main/normal/logs/regions-0-401215.fa.log 2>&1)...
** 0 just got out of the pool [PID: 624240 | exit code: 0 | exit signal: 0 | core dump: 0]
Merge DBs...
Load reference coverage...
Load loc2keys DB...
Computing hom/het state...
Num. Homozygous: 0
Num. Heterozygous: 0

Dfs limit: 0
Partial alignments: 0
Cycles: 0
OK assemblies: 0
Exceptions: 0
Repeats: 0

Printing reference coverage to file...
Printing loc2key DB to file...
-- Exporting variants to file
Loading targets from BED file...185636 targets (filtered 0 overlapping).
[#SNPs: 0 | #Ins: 0 | #Del: 0 | Tot: 0]
Export: elapsed time: 0 day(s) 0 hour(s) 0 minute(s) 0 second(s)
FindVariants elapsed time: 0 day(s) 2 hour(s) 41 minute(s) 29 second(s)
-- Detect mutations on tumor
-- Print parameters to /outdir/main/tumor/parameters.txt
Loading targets from BED file...185636 targets (filtered 0 overlapping).
Assembly Exons
start assembly of 401216 regions.
stepSize: 401216
** 0 started, pid: 2433299
1. [0..401215]
Command failure: microassembly (/rds/general/user/cd3417/home/anaconda3/envs/analysis_Clara/share/scalpel-0.5.4-1/Microassembler/Microassembler -R -I -C -F 1000000 -k 25 -K 90 -M 3 -l 25 -c 5 -x 0.01 -d 2 -u 10000 -b 1 -p /outdir/main/tumor -m bamfile.bam -g readgroups.txt  -r regions-0-401215.fa >/outdir/main/tumor/logs/regions-0-401215.fa.log 2>&1)...
** 0 just got out of the pool [PID: 2433299 | exit code: 0 | exit signal: 0 | core dump: 0]
Merge DBs...
Load reference coverage...
Load loc2keys DB...
Computing hom/het state...
Num. Homozygous: 0
Num. Heterozygous: 0

Dfs limit: 0
Partial alignments: 0
Cycles: 0
OK assemblies: 0
Exceptions: 0
Repeats: 0

Printing reference coverage to file...
Printing loc2key DB to file...
-- Exporting variants to file
Loading targets from BED file...185636 targets (filtered 0 overlapping).
[#SNPs: 0 | #Ins: 0 | #Del: 0 | Tot: 0]
Export: elapsed time: 0 day(s) 0 hour(s) 0 minute(s) 0 second(s)
FindVariants elapsed time: 0 day(s) 2 hour(s) 14 minute(s) 27 second(s)
-- Loading mutations and coverage info
load variants for normal...
load variants for tumor...
load coverage for normal...
load coverage for tumor...
load loc2key for for normal...
load loc2key for for tumor...
remove coverage file for normal...
remove coverage file for tumor...
-- Compute best state for each variant
-- Finding somatic mutations
-- Exporting variants to file
Loading targets from BED file...185636 targets (filtered 0 overlapping).
[#SNPs: 0 | #Ins: 0 | #Del: 0 | Tot: 0]
Export: elapsed time: 0 day(s) 0 hour(s) 0 minute(s) 1 second(s)
Loading targets from BED file...185636 targets (filtered 0 overlapping).
[#SNPs: 0 | #Ins: 0 | #Del: 0 | Tot: 0]
Export: elapsed time: 0 day(s) 0 hour(s) 0 minute(s) 1 second(s)
FindSomatic elapsed time: 0 day(s) 4 hour(s) 56 minute(s) 0 second(s)
Extract coordinates of candidates...Loading targets from BED file...185636 targets (filtered 0 overlapping).
No candidate calls to validate. Nothing to do! exit.

**Comment by roryk** [comment]
Hmm.. Does this not exist?

`/rds/general/user/cd3417/home/anaconda3/envs/analysis_Clara/share/scalpel-0.5.4-1/Microassembler/Microassembler`

It looks like it is running it, but it is failing. Does your BAM file look reasonable?

**Comment by clersdom** [comment]
Sorry for the late response. No it does not exist as below

`ls: cannot access /rds/general/user/cd3417/home/anaconda3/envs/analysis_Clara/share/scalpel-0.5.4-1/Microassembler/Microassembler: No such file or directory`

Yes, the BAM files are ok. Have run other jobs with them. In addition, a colleague has run the same job with another sample that is confirmed to have indels and has got the same error. Seems that could have something to do with the installation? 
We both installed scalpel by using anaconda.

**Comment by roryk** [comment]
Thanks, is this a scalpel issue or a bcbio issue? If it's a scalpel issue you're probably better off talking to the scalpel team: http://scalpel.sourceforge.net/
