### ISSUE TITLE
User 'bcbio' still being referenced instead of 'bioconda'

### ISSUE THREAD

**Issue by erichpeterson** [chapmanb/bcbio-nextgen-vm#139]
Several references the conda user 'bcbio' are still present, which causes upgrading to fail. Need to change to 'biconda'. See one such instance in:

docker.bcbiovm.install.py

```
subprocess.check_call([conda_bin, "install", "--yes",
                               "-c", "https://conda.binstar.org/bcbio",
                               "bcbio-nextgen-vm"])
```

**Comment by chapmanb** [comment]
Erich;
Apologies about missing these references. I've updated them and the conda package so it should now upgrade cleanly. Thanks so much for the heads up.
