### ISSUE TITLE
Bcbio Stopping vm Cluster I want to keep the cluster.

### ISSUE THREAD

**Issue by mortunco** [chapmanb/bcbio-nextgen-vm#147]
Hi,

I have couple questions related with starting and stopping cluster.

1. Once we start the cluster is there a way to stop is without terminating it ? I know that I cannot do it by bcbio. because ````bcbio_vm.py aws cluster stop``` terminates cluster.
2. I tried to stop the instances manually from EC2 console. I stopped it and re started however, I couldnt connect it back again with ```bcbio_vm.py aws cluster ssh```. Instead I copied the bcbio key to the text file and connect it with  ```ssh -i bcbio.pem ubuntu@ip```  from my local.  This method worked. 

I think i should be able to connect back with was ssh command of bcbio. 

Thank you for the valuable information,

Best regards,

Tunc.

**Comment by chapmanb** [comment]
Tunc;
We unfortunately don't have a way to stop/restart clusters with the bcbio_vm.py command line features. As you discovered it's a bit hard to do as the restarted instances have new keys, so the locally stored information about the clusters gets out of date.

We're actively working on generalizing bcbio to use a community representation of workflows with the Common Workflow Language (http://bcbio-nextgen.readthedocs.org/en/latest/contents/cwl.html) so will hopefully in the near future move to a community developed tool that supports features like this to improve the AWS integration (like cgcloud and toil: https://github.com/BD2KGenomics/cgcloud https://github.com/BD2KGenomics/toil).

Sorry to not have something immediately ready but hope this helps.
