### ISSUE TITLE
Using bcbio_setup_genome.py with bcbio-nextgen-vm?

### ISSUE THREAD

**Issue by tomsing1** [chapmanb/bcbio-nextgen-vm#149]
I have installed bcbio-nexten-vm following the steps outlined on the [bcbio-nextgen-vm landing page](https://github.com/chapmanb/bcbio-nextgen-vm). Before I can launch an analysis via `bcbio_vm.py run` I need to add a custom genome. 

Is it possible to build the genome indices with this setup, e.g. given that the tools are within the bcbio/bcbio docker container?

Perhaps there is a way to run the `bcbio_setup_genome.py` command somehow?
Thanks a lot for any ideas!

**Comment by chapmanb** [comment]
Thomas;
Unfortunately, we don't currently have a way to run this script inside the Docker container, but it is included with the bcbio_vm distribution in:
```
/path/to/bcbio/anaconda/bin/bcbio_setup_genome.py
```
It should have all Python dependencies installed but not necessarily the external tools it called. But we haven't yet tested it with this setup so I'm not sure how well it will work. We will definitely migrate this functionality but likely as part of our new effort to support the Common Workflow Language with Docker (http://bcbio-nextgen.readthedocs.org/en/latest/contents/cwl.html).

Is installing standard bcbio_nextgen.py an option now if you need to add in custom genomes? 

Hope this helps.

**Comment by tomsing1** [comment]
Thank you for your quick response and for pointing out the location of the `bcbio_setup_genome.py` script.  Unfortunately, it doesn't seem to run without external tools (e.g. picard). 

I will go ahead and install the standard `bcbio_nextgen.py` as you recommended and am looking forward to CWL options you guys are working on!

**Comment by fgvieira** [comment]
@chapmanb Has this issue been fixed? I mean, is it possible to add a custom genome to bcbio-vm?
thanks,
