### ISSUE TITLE
Reopening issue about VPC creation in the wrong zone

### ISSUE THREAD

**Issue by tomsing1** [chapmanb/bcbio-nextgen-vm#157]
I have encountered the same problem marked as resolved in #155: 
When I am trying to create a VPC in `us-west-2`, the VPC is always created in `us-east-1` instead.

As advised above I executed 
`export AWS_DEFAULT_REGION=us-west-2`
before running 
`bcbio_vm.py aws vpc`
but the VPC kept popping up in `us-east-1`.

For good measure, I also changed all `east-1` into `west-2` in `~/.bcbio/elasticluster/config`, but that didn't help, either.

Any ideas what's going on?

I am running the following versions:
```
bcbio-nextgen             1.0.1a0                  py27_0    bioconda
bcbio-nextgen-vm          0.1.0a                  py27_86    bioconda
```

**Comment by tomsing1** [comment]
Exporting the `AWS_DEFAULT_REGION` environment variable didn't work, but creating a `.boto` file with the following content did the trick:

```
[Boto]
ec2_region_name = us-west-2
ec2_region_endpoint = ec2.us-west-2.amazonaws.com
```

**Comment by chapmanb** [comment]
Thomas -- thanks so much for following up with a solution, that's a big help for anyone doing this in non us-east-1 regions in the future. Hope additional things go smoother for you going forward.
