### ISSUE TITLE
elasticloud not installed?

### ISSUE THREAD

**Issue by willmclaren** [chapmanb/bcbio-nextgen-vm#165]
I'm following the instructions to set up bcbio-vm from [here](http://bcbio-nextgen.readthedocs.io/en/latest/contents/cloud.html)

Minor point, the third line of installation instructions should read:

```~/install/bcbio-vm/anaconda/bin/conda install --yes -c conda-forge -c bioconda bcbio-nextgen-vm```

I then reach the point of setting up the VPC, and hit this error:

```
$ bcbio_vm.py aws vpc --region=us-east-1
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_vm.py", line 331, in <module>
    args.func(args)
  File "/home/ubuntu/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbiovm/aws/vpc.py", line 12, in bootstrap
    vpc_info = setup_vpc(args, args.region)
  File "/home/ubuntu/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbiovm/aws/vpc.py", line 53, in setup_vpc
    cluster_config = common.ecluster_config(args.econfig, args.cluster)
  File "/home/ubuntu/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbiovm/aws/common.py", line 94, in ecluster_config
    from elasticluster.conf import Configurator
ImportError: No module named elasticluster.conf
```

This happens both on my local machine (Ubuntu/Windows Subsystem for Linux) and in a clean AWS Ubuntu server instance.

**Comment by chapmanb** [comment]
Will;
Apologies about the issue, we've been deprecating the elasticluster and custom AWS work in favor of supporting Common Workflow Language (http://bcbio-nextgen.readthedocs.io/en/latest/contents/cwl.html) so no longer install elasticluster by default. At this point I'd probably not recommend using the elasticluster and custom cloud approach, and would be happy to try and get you going in the right direction with an understanding of what you'd like to do. Apologies, we're in a bit of a transition as we move to use CWL but hoping that it will provide a better experience on the cloud long term.

Also, I'm happy to fix the docs for installation but that line looks like what we currently have so not sure what to change. Sorry, I might be blind to typos this morning and not seeing it.

Hope this helps and thanks for exploring bcbio-vm.

**Comment by willmclaren** [comment]
Thanks Brad. Basically I'm looking to get a best-practices variant calling pipeline (GATK to start with) set up in AWS, and bcbio-vm looked like an easy shortcut to what I wanted. In the long run I'd like the pipeline to be parallel and distributable, but in the short term running on a single machine would be OK so I can probably get going most easily with the bcbio Docker image?

**Comment by chapmanb** [comment]
Will -- thanks makes sense. If running on a single machine works the approach I take for my AWS runs is to use an attached disk where I install bcbio and my data and then spin up and down instances that attach it for running analyses. The process is described with some ansible scripts for automation here:

https://github.com/chapmanb/bcbio-nextgen/tree/master/scripts/ansible

We're working hard on the more general case of running and distributing these. If using DNAnexus or SevenBridges is an option we have made a lot of progress there using CWL. We hope to also have other options coming but none ready to run real pipelines on right now.

Hope this helps some and please let me know if I can help with anything at all on getting setup.
