### ISSUE TITLE
GATK4

### ISSUE THREAD

**Issue by willmclaren** [chapmanb/bcbio-nextgen-vm#166]
Hi Brad,

I'm happily using bcbio-vm now for my variant calling runs.

I'd like to update my pipeline to use GATK4 - how would I go about doing this and verifying that bcbio-vm is using 4.0.0 and not the pre-release beta?

**Comment by chapmanb** [comment]
Will;
Great to hear things are working well with bcbio-vm. Are you using Docker containers or a local installation for running? If Docker, are you using bcbio/bcbio containers from Docker Hub or bcbio/bcbio-vc from quay.io? The quay.io ones are updated with the latest release and GATK 4.0.1.0 and I trigger a rebuild of bcbio/bcbio as well so it will have the latest. If a local installation an update to the latest release (1.0.8) or development will also use the GATK 4 release. Hope one of these options works for you.

**Comment by willmclaren** [comment]
I'm using docker; I believe from the logs it's using bcbio/bcbio from Docker Hub - how can I get it to use the quay.io one? I notice there's an error in the build log on Docker Hub, https://hub.docker.com/r/bcbio/bcbio/builds/

**Comment by chapmanb** [comment]
Will -- thanks for following up and sorry about the bcbio/bcbio build issues on Docker Hub. That's now integrated and if you update (`docker pull bcbio/bcbio`) will get the latest version with GATK 4.0.1.0. This will be reflected in the `provenance/programs.txt` file when you run.

You can use the quay.io repository with:
```
bcbio_vm.py run --image quay.io/bcbio/bcbio-vc
```
I'm hopeful to move over to using CWL for this local run case which supports these by default so we can deprecate the bcbio/bcbio version but either choice will work well now, and please let me know if you run into any issues. Thanks again.
