### ISSUE TITLE
Please build updated Conda package for elasticluster

### ISSUE THREAD

**Issue by jwm** [chapmanb/bcbio-nextgen-vm#49]
I finished the work for https://github.com/gc3-uzh-ch/elasticluster/pull/144 recently and pushed an updated bcbio branch; would you update the Conda package and give the result a try, please? Building a new cluster works for me, but it'd be nice to have someone else double check.

**Comment by jwm** [comment]
I forgot to mention, you'll have to enable secure SSH host key fetching with:

```
ssh_hostkeys_from_console_output=True
```

on the `[cluster/bcbio]` section.

**Comment by chapmanb** [comment]
John;
Thanks much for this. I updated bcbio-vm and elasticluster to include these. Much appreciated.
