### ISSUE TITLE
fails aws info if you have deafult VPC without TAG NAME

### ISSUE THREAD

**Issue by lpantano** [chapmanb/bcbio-nextgen-vm#53]
Hi, not urgent at all, but I was getting an error when doing `aws info` because you always have a VPC by default without a `NAME`, so i think bcbio_vm breaks here:

https://github.com/chapmanb/bcbio-nextgen-vm/blob/master/bcbiovm/aws/info.py#L87

maybe put some code before to skip that VPC.

thanks!

**Comment by chapmanb** [comment]
Thanks Lorena for the heads up.
