### ISSUE TITLE
collectl and lustre support

### ISSUE THREAD

**Issue by kern3020** [chapmanb/bcbio-nextgen-vm#55]
Hello, 

I was looking at the "Running Lustre" section and noticed collectl. Wondering what it is, I went to the website: http://collectl.sourceforge.net/. It says "Remember, lustre support is going away the summer of 2015". Is this a concern for us? 

-jk

**Comment by chapmanb** [comment]
John;
Thanks for looking at this. @jwm has bcbio already using the custom plugin:

https://github.com/chapmanb/bcbio-nextgen-vm/blob/master/ansible/roles/icel/tasks/main.yml

so we don't have any worries here. Thanks again.
