### ISSUE TITLE
google cloud support

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen-vm#56]
Any plans to support google compute engine? If not in the cards for the near future, do you have any recommendations on a more generic cloud workflow setup? It seems elasticcluster has some support for google so that's a plus.

**Comment by chapmanb** [comment]
Daryl;
We don't have any near terms plans to port to Google Compute Engine. It would be great to support this, but is a bigger scale project we don't have funding to work on right now. Most of the internal code using Elasticluster should port reasonably well, but we'd have to code the top level parts setting up the infrastructure and permissions to work with GCE.

What is motivating a desire to run on GCE? Are there existing issues with the AWS infrastructure that we could improve?

**Comment by dwaggott** [comment]
Resources, collaboration and proximity to Stanford. Let's see if I can get
someone to do a bit of digging.

**Comment by guillermo-carrasco** [comment]
Closing the issue since this is not in the roadmap for the moment. Please @dwaggott let us know if you have any feedback about AWS or that collaboration you mentioned :)
