### ISSUE TITLE
update conda install with system python

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen-vm#59]
When following the instructions in the readme file on installing conda using the sytem python, I get the following error:

<code>
Error: This installation of conda is not initialized. Use 'conda create -n
envname' to create a conda environment and 'source activate envname' to
activate it.
 Note that pip installing conda is not the recommended way for setting up your
 system.  The recommended way for setting up a conda system is by installing
 Miniconda, see: http://repo.continuum.io/miniconda/index.html
</code>

perhaps the documentation should be updated?

Greetings
Matthias

**Comment by chapmanb** [comment]
Matthias;
Thanks for the heads up, I'd missed that they no longer actively support the system python approach. I removed this from the docs and now only suggest using an isolated Miniconda. Thanks again.
