### ISSUE TITLE
Module 'bcbio.pipeline.genome' has no 'S3_INFO'

### ISSUE THREAD

**Issue by alexandrucoman** [chapmanb/bcbio-nextgen-vm#60]
Hello,

In [bcbiovm.docker.devel](https://github.com/chapmanb/bcbio-nextgen-vm/blob/master/bcbiovm/docker/devel.py#L212-213) the ```S3_INFO``` dictionary from [bcbio.pipeline.genome](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/pipeline/genome.py) is required but it doesn't exist.

```
    bucketname = genome.S3_INFO["bucket"]
    keyname = genome.S3_INFO["key"].format(build=gbuild, target=target)
```

Thanks,
Alex

**Comment by chapmanb** [comment]
Alex;
Apologies, I hadn't refactored this to use the new objectstore abstraction in bcbio-nextgen. I pushed some fixes which use the new structure and will work on testing this with some new uploads. Thanks much for the heads up on this.
