### ISSUE TITLE
Data fail to install

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen-vm#78]
When I try to install data on MacOSx with the following command:

bcbio_vm.py --datadir=~/install/bcbio-vm/data install --data --tools --genomes GRCh37 --aligners bwa

I get the following error message and no data file are installed.

Thanks for your support!

INFO: Extracting RNA-seq references: GRCh37-rnaseq-2014-07-14.tar.xz
tar: GRCh37/rnaseq-2014-07-14/ref-transcripts.gtf.db: Wrote only 5120 of 10240 bytes
tar: GRCh37/rnaseq-2014-07-14/ref-transcripts.genePred: Cannot write: No space left on device
tar: GRCh37/rnaseq-2014-07-14/ref-transcripts.refFlat: Cannot write: No space left on device
tar: GRCh37/rnaseq-2014-07-14/ref-transcripts.dexseq.gff: Cannot write: No space left on device
tar: GRCh37/rnaseq-2014-07-14/ref-transcripts-mask.gtf: Cannot write: No space left on device
tar: GRCh37/rnaseq-2014-07-14/rRNA.gtf: Cannot write: No space left on device
tar: GRCh37/rnaseq-2014-07-14/rRNA.gtf.db: Cannot write: No space left on device
tar: GRCh37/rnaseq-2014-07-14/rRNA.interval_list: Cannot write: No space left on device
tar: GRCh37/rnaseq-2014-07-14/tophat/GRCh37_transcriptome.gff: Cannot write: No space left on device
tar: GRCh37/rnaseq-2014-07-14/tophat/GRCh37_transcriptome.fa: Cannot write: No space left on device
tar: GRCh37/rnaseq-2014-07-14/tophat/GRCh37_transcriptome.fa.tlst: Cannot write: No space left on device
tar: GRCh37/rnaseq-2014-07-14/tophat/GRCh37_transcriptome.ver: Cannot write: No space left on device
tar: GRCh37/rnaseq-2014-07-14/tophat/GRCh37_transcriptome.3.bt2: Cannot write: No space left on device
tar: GRCh37/rnaseq-2014-07-14/tophat/GRCh37_transcriptome.4.bt2: Cannot write: No space left on device
tar: GRCh37/rnaseq-2014-07-14/tophat/GRCh37_transcriptome.1.bt2: Cannot write: No space left on device
tar: GRCh37/rnaseq-2014-07-14/tophat/GRCh37_transcriptome.2.bt2: Cannot write: No space left on device
tar: GRCh37/rnaseq-2014-07-14/tophat/GRCh37_transcriptome.rev.1.bt2: Cannot write: No space left on device
tar: GRCh37/rnaseq-2014-07-14/tophat/GRCh37_transcriptome.rev.2.bt2: Cannot write: No space left on device
tar: GRCh37/rnaseq-2014-07-14/tophat/large_exons.gtf: Cannot write: No space left on device
tar: Exiting with failure status due to previous errors

Fatal error: local() encountered an error (return code 2) while executing 'xz -dc GRCh37-rnaseq-2014-07-14.tar.xz | tar -xpf -'

Aborting.
Upgrading bcbio-nextgen data files
Setting up virtual machine
[localhost] local: cat /etc/*release | grep DISTRIB_CODENAME | cut -f 2 -d =
[localhost] local: cat /proc/version
[localhost] local: cat /etc/issue
[localhost] local: cat /etc/*release | grep DISTRIB_CODENAME | cut -f 2 -d =
[localhost] local: echo $HOME
[localhost] local: uname -m
[localhost] local: mkdir -p /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37
[localhost] local: pwd
[localhost] local: echo $HOME
[localhost] local: mkdir -p '/root/tmp/cloudbiolinux/2d48e41c-2b04-38f0-96e7-e3ca48f3e875'
[localhost] local: wget --continue --no-check-certificate -O GRCh37-rnaseq-2014-07-14.tar.xz 'https://s3.amazonaws.com/biodata/annotation/GRCh37-rnaseq-2014-07-14.tar.xz'
[localhost] local: mv GRCh37-rnaseq-2014-07-14.tar.xz /usr/local/share/bcbio-nextgen/genomes/Hsapiens
[localhost] local: rm -rf /root/tmp/cloudbiolinux/2d48e41c-2b04-38f0-96e7-e3ca48f3e875
[localhost] local: xz -dc GRCh37-rnaseq-2014-07-14.tar.xz | tar -xpf -
local() encountered an error (return code 2) while executing 'xz -dc GRCh37-rnaseq-2014-07-14.tar.xz | tar -xpf -'
' returned non-zero exit status 1
Stopping docker container

bcbio-nextgen-vm updated with latest bcbio-nextgen code and third party tools and biological data

**Comment by chapmanb** [comment]
Thanks for trying out bcbio. It looks like the disk you're installing on ran out of space:
```
Cannot write: No space left on device
tar: Exiting with failure status due to previous errors
```
If you clear up some additional space and restart it should kick off where it left off. Hope this helps.
