### ISSUE TITLE
GRCh37 with decoy sequences

### ISSUE THREAD

**Issue by nstongcelmatix** [chapmanb/bcbio-nextgen-vm#89]
I'm trying to run the gatk-variant template using the reference sequence with the decoy sequences.  It is also included the gatk resource files as human_g1k_v37_decoy.fasta.  To do so I need a docker image of the bcbio-nextgen with that reference sequence added?  Is that available somewhere or would I need to make my own?

**Comment by chapmanb** [comment]
Unfortunately we don't have a clean way to do custom genome builds with the current Docker implementation on AWS. The reference sequences are not contained in the Docker image, which only has the tools, and instead get installed outside and linked into the container during runs. On AWS, they are downloaded on demand from pre-built genomes. At this point on AWS your best bet for custom genomes is to create a custom AMI with the data you need. 

If you're running locally, you can setup a custom genome with the build you want using the scripts for bcbio:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#adding-custom-genomes

In the mid-term we're working on supporting GRCh38 which should get the benefits of decoy sequences plus the new build. This will be available on AWS once we have it tested and validated.

Sorry to not have a good solution right now but hope this helps.

**Comment by guillermo-carrasco** [comment]
Closing issue, please @nstongcelmatix feel free to re-open if you have further questions. You may also be interested in [the GRCh38 work](http://bcb.io/2015/09/17/hg38-validation/) Brad mentioned.

Thanks!
