### ISSUE TITLE
S3 Mount on Cluster

### ISSUE THREAD

**Issue by sarmadym** [chapmanb/bcbio-nextgen-vm#96]
Followed instructions on AWS installation of bcbio-nextgen-vm. I start the cluster from an ec2 instance after I ssh to cluster and try to run a pipeline, I receive an error that the fastq files cannot be accessed. They are on an S3 bucket. Do I need to anything to mount S3 on the cluster and its nodes? Or strictly following the instructions should work?

**Comment by chapmanb** [comment]
Thanks for trying out bcbio and sorry about the issues. Would you be able to post the exact error message you received so we can provide specific thoughts/recommendations?

Generally, you don't have mount S3 or do anything special. You do have to ensure the user you're running with has permission to access the S3 bucket to retrieve data from. Practically, can the user you ran the bcbio AWS setup as (https://bcbio-nextgen.readthedocs.org/en/latest/contents/cloud.html#aws-setup) access the S3 bucket with the files? If not, adjusting these permissions will get things working.

Hope this helps.

**Comment by guillermo-carrasco** [comment]
Closing issue, please @sarmadym feel free to re-open is you still have problems with S3 data pulling. Thank you!
